DELIMITER $$

CREATE EVENT `truncate_course_audit_monthly`
ON SCHEDULE EVERY 1 MONTH
STARTS '2025-12-04 19:34:05'
ON COMPLETION NOT PRESERVE
ENABLE
DO
    DELETE FROM `course_audit` 
    WHERE `changed_at` < DATE_SUB(NOW(), INTERVAL 1 MONTH) 
$$

DELIMITER ;